django_grocery_app/urls.py
from django.urls import path,re_path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth
urlpatterns = [
    path('', grocery_home,name = 'index'),
    path('add/',grocery_add,name ='add'),
    re_path(r'^(?P<pk>\d+)/update/$',grocery_update,name = 'update'),
    re_path(r'^(?P<pk>\d+)/details/$',grocery_details,name = 'detail'),
    path('logout/user/login/', auth.LogoutView.as_view(), {'template_name': 'logged_out.html'}, name = 'logout')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_grocery_bag/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django_grocery_app.urls')),
    path('user/',include('users.urls'))
]

users/urls.py
from django.urls import path
from users import views as user_view
from django.urls import reverse_lazy

app_name = 'custom_auth'
urlpatterns = [
    path('register/', user_view.RegisterView.as_view(), name ='register'),
    path('login/', user_view.LoginView.as_view(), name ='login'),
    
]

django_grocery_app/models.py
from django.db import models
from users.models import User
CHOICES = [
    ('Available', 'Available'),
    ('Out Of Stock', 'Out Of Stock'),
]
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Category(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name


class GroceryBag(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    product_name = models.CharField(max_length=20)
    product_image = models.ImageField(upload_to = user_directory_path)
    product_price = models.CharField(max_length=20)
    product_color = models.CharField(max_length=20)
    product_category = models.ManyToManyField(Category)
    product_stock_status = models.CharField(choices=CHOICES,max_length=20)

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .manager import UserManager

class User(AbstractBaseUser):
    """User model."""
    email = models.EmailField(_('email address'), unique=True)
    name = models.CharField(_('name'), max_length=50, blank=False)
    is_superadmin = models.BooleanField(_('is_superadmin'), default=False)
    is_active = models.BooleanField(_('is_active'), default=True)
    is_staff = models.BooleanField(default=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
    def has_perm(self, perm, obj=None):
        return self.is_superadmin
    def has_module_perms(self, app_label):
        return self.is_superadmin

django_grocery_app/forms.py
from django import forms
from django.db import models
from django.db.models import fields 
from .models import GroceryBag
from parsley.decorators import parsleyfy

@parsleyfy
class GroceryBagForm(forms.ModelForm):
   class Meta:
        model= GroceryBag 
        fields = '__all__'
        exclude = ('user',)
    
        widgets = {
            'product_category': forms.Select(),
        }
        
    

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from parsley.decorators import parsleyfy

@parsleyfy
class RegisterForm(forms.ModelForm):
    """user signup form"""
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ('email', 'name', 'password',)


@parsleyfy
class LoginForm(forms.Form):
    """user login form"""
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

django_grocery_app/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .models import GroceryBag
from django.http import HttpResponse
from .forms import GroceryBagForm
from django.contrib.auth.decorators import login_required



def grocery_add(request):
    if request.method == 'POST':
        
        form = GroceryBagForm(request.POST, request.FILES or None)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            print(product.user)
            product.save()
            return HttpResponseRedirect("/")
        else:
            print(form.errors)
            return  HttpResponse(form.errors)
    else:
        form = GroceryBagForm ()
    return render(request, 'add.html', {'form' : form })

def grocery_update(request,pk):
    obj = get_object_or_404(GroceryBag, id = pk)
    form = GroceryBagForm(request.POST or None, instance = obj)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")
    return render(request, "update.html", {'form':form})
def grocery_details(request,pk):
    obj = get_object_or_404(GroceryBag, id = pk)
    form = GroceryBagForm(request.POST or None, instance = obj)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")
    return render(request, "detail.html", {'form':form,'obj':obj})



@login_required(login_url='/user/login/')
def grocery_home(request):

    product_list = GroceryBag.objects.all()
    return render (request,'index.html',{'grocery' : product_list})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import RegisterForm,LoginForm
from django.template.loader import get_template
from django.template import Context
from .models import User
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.http import HttpResponse,HttpResponseRedirect



class RegisterView(FormView):
    """sign up user view"""
    form_class = RegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('custom_auth:login')

    def form_valid(self, form):

        user = form.save(commit=False)
        user.save()
        login(self.request, user)
        if user is not None:
            return HttpResponseRedirect(self.success_url)

        return super().form_valid(form)



class LoginView(FormView):


    form_class = LoginForm
    success_url = reverse_lazy('index')
    template_name = 'login.html'

    def form_valid(self, form):

        credentials = form.cleaned_data
        email = credentials['email']
        password = credentials['password']
        try:
            user = User.objects.get(email=email)
        except:
            user = None
        if user is not None and user.password == password :
            login(self.request, user)
            return HttpResponseRedirect(self.success_url)

        else:
            messages.add_message(self.request, messages.INFO, 'Wrong credentials\
                                please try again')
            return HttpResponseRedirect(reverse_lazy('custom_auth:login'))

templates/add.html
{% load static %}
{% load widget_tweaks %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Add List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'js/parsley.js' %}">
        <script type = "text/javascript">
   
            // Form validation code will come here.
            function validate() {
            
            
               if( document.loginform.product_name.value == "" ) {
                  alert( "Please provide your Product Name!" );
                  document.loginform.email.focus() ;
                  return false;
               }
             
               if( document.loginform.product_price.value == "" ) {
                  alert( "Please provide your Product Price!" );
                  document.loginform.product_price.focus() ;
                  return false;
               }
               if( document.loginform.product_color.value == "" ) {
                  alert( "Please provide your Product Color!" );
                  document.loginform.product_price.focus() ;
                  return false;
               }
               if( document.loginform.product_name.value == "" ) {
                  alert( "Please provide your Product Name!" );
                  document.loginform.email.focus() ;
                  return false;
               }
               
               return( true );
            }
            
            function fileValidation() {
            var fileInput = 
                document.getElementById('file');
              
            var filePath = fileInput.value;
          
            // Allowing file type
            var allowedExtensions = 
                    /(\.jpg|\.jpeg|\.png|\.gif)$/i;
              
            if (!allowedExtensions.exec(filePath)) {
                alert('Invalid file type');
                fileInput.value = '';
                return false;
            } 
            else 
            {
              
                // Image preview
                if (fileInput.files && fileInput.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        document.getElementById(
                            'imagePreview').innerHTML = 
                            '<img src="' + e.target.result
                            + '"/>';
                    };
                      
                    reader.readAsDataURL(fileInput.files[0]);
                }
            }
        }
      </script>
    </head>
    <body>
        <div class="container mt-5">
            <h1>Add Product</h1>
            <form action="{% url 'add' %}" method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                <div class="form-group">
                    <label>Product name</label>
                    {{form.product_name | attr:"class:form-control" }}
                </div>
                <div class="form-group">
                    <label>Product Image</label>
                    {{form.product_image | attr:"class:form-control" | attr:"id:file" | attr:"onchange:return fileValidation()"}} 
                   </div>
                   <div id="imagePreview"></div>
            
                <div class="form-group">
                    <label>Product Price</label>
            
                    {{form.product_price | attr:"class:form-control" | attr:"type:number"}}
                </div>
                <div class="form-group">
                    <label>Product Color</label>
            
                    {{form.product_color | attr:"class:form-control"}}
                </div>
                <div class="form-group">
                    <label>Product Category</label>
            
                    {{form.product_category | attr:"class:form-control"}}
                </div>
                <div class="form-group">
                    <label>Product Status </label>
            
                    {{form.product_stock_status | attr:"class:form-control"}}
                </div>
                
                <div class="form-group">
                   
                    <input type="submit" value="Add" class="btn btn-danger">
                </div>
            </form>
        </div>
    </body> 
</html>

templates/detail.html
{% load static %}
{% load widget_tweaks %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Update List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container mt-5">
            <h1>Product Detail</h1>
            <img src="{{obj.product_image.url}}" class="img-thumbnail mx-auto d-block" alt="...">
            <form >
                <div class="form-group">
                    <label>Product name</label>
                    {{form.product_name | attr:"class:form-control" | attr:"readonly" }}
                </div>
                <div class="form-group">
                    <label>Product Price</label>
                    {{form.product_price | attr:"class:form-control" | attr:"readonly" }}
                   </div>
                   <div class="form-group">
                    <label>Product Color</label>
            
                    {{form.product_color | attr:"class:form-control" | attr:"disabled:true"  }}
                </div>
                <div class="form-group">
                    <label>Product Category</label>
            
                    {{form.product_category | attr:"class:form-control" | attr:"disabled:true"  }}
                </div>
                <div class="form-group">
                    <label>Product Stock</label>
                    {{form.product_stock_status | attr:"class:form-control" | attr:"disabled:true" }}
                </div>
            </form>
        </div>
    </body> 
</html>

templates/index.html
{% load static %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>View List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="col-md-12 text-center">
            <a href="{% url 'logout' %}" class="btn btn-danger btn-lg float-right" role="button" >LogOut</a>
        </div>
        <div class="container mt-5">
            <!-- Grocery Cards -->
            
            <div class="col-md-12 text-center">
                <a href="{% url 'add' %}" class="btn btn-primary btn-lg" role="button" >Add New Product</a>
            </div>
            
            <div class="row mt-4">
                {% for product in grocery %}
                <!--- -->
                <!-- Loop This -->
                <div class="col-lg-4">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{product.product_image.url}}" alt="Card image cap">
                        <div class="card-body">
                            <a class="card-block stretched-link text-decoration-none" href="{% url 'detail' product.id %}">
                          <h5 class="card-title">{{product.product_name}}</h5>
                          <h6 class="card-subtitle mb-2 text-muted"> Price : ₹ {{product.product_price}} </h6>
                          <h6 class="card-subtitle mb-2 text-muted"> Color :  {{product.product_color}} </h6>
                                <h6 class="card-subtitle mb-2 text-muted"> Stock :  {{product.product_stock_status}} </h6>
                        </a>
                        {% if product.user == request.user %}
                        <a href="#" class="btn btn-primary">Edit Product</a>
                        {% endif %}
                        </div>
                      </div>
                </div>
                {% endfor %}
                <!-- // Loop -->
                

            </div>
        </div>
    </body>
</html>

templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
    <link rel="stylesheet" href="{% static 'js/parsley.js' %}">
    <title>Login Form </title>
    <script type = "text/javascript">
   
           // Form validation code will come here.
           function validate() {
           
           
              if( document.loginform.email.value == "" ) {
                 alert( "Please provide your Email!" );
                 document.loginform.email.focus() ;
                 return false;
              }
            
              if( document.loginform.password.value == "-1" ) {
                 alert( "Please provide your Password!" );
                 return false;
              }
              return( true );
           }
  
     </script>
  </head>
  <body>
    <div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
      
        <div class="card card0 border-0">
            <div class="row d-flex">
                <div class="col-lg-6">
                    <div class="card1 pb-5">
                        <div class="row"> <img src="https://i.imgur.com/CXQmsmF.png" class="logo"> </div>
                        <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <img src="https://i.imgur.com/uNGdWHi.png" class="image"> </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <form name="loginform" action="{% url 'custom_auth:login' %}" method="post"   onsubmit = "return(validate());" data-parsley-validate>
                        {% csrf_token %}
                    <div class="card2 card border-0 px-4 py-5">

                        <div class="row px-3 mb-4">
                            <div class="line"></div> 
                            <div class="line"></div>
                        </div>
                        <div class="row px-3"> {{form}} </div>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Login</button> </div>
                        <div class="row mb-4 px-3"> <small class="font-weight-bold">Don't have an account? <a class="text-danger " href="{% url 'custom_auth:register' %}">Register</a></small> </div>
                    </div>
                </form>
                </div>
            </div>
            <div class="bg-blue py-4">
                <div class="row px-3"> <small class="ml-4 ml-sm-5 mb-2">Copyright &copy; 2019. All rights reserved.</small>
                    <div class="social-contact ml-4 ml-sm-auto"> <span class="fa fa-facebook mr-4 text-sm"></span> <span class="fa fa-google-plus mr-4 text-sm"></span> <span class="fa fa-linkedin mr-4 text-sm"></span> <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span> </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/logout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
    <link rel="stylesheet" href="{% static 'js/parsley.js' %}">
    <title>Login Form </title>
    <script type = "text/javascript">
   
           // Form validation code will come here.
           function validate() {
           
           
              if( document.loginform.email.value == "" ) {
                 alert( "Please provide your Email!" );
                 document.loginform.email.focus() ;
                 return false;
              }
            
              if( document.loginform.password.value == "-1" ) {
                 alert( "Please provide your Password!" );
                 return false;
              }
              return( true );
           }
  
     </script>
  </head>
  <body>
    <div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
      
        <div class="card card0 border-0">
            <div class="row d-flex">
                <div class="col-lg-6">
                    <div class="card1 pb-5">
                        <div class="row"> <img src="https://i.imgur.com/CXQmsmF.png" class="logo"> </div>
                        <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <img src="https://i.imgur.com/uNGdWHi.png" class="image"> </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <form name="loginform" action="{% url 'custom_auth:login' %}" method="post"   onsubmit = "return(validate());" data-parsley-validate>
                        {% csrf_token %}
                    <div class="card2 card border-0 px-4 py-5">

                        <div class="row px-3 mb-4">
                            <div class="line"></div> 
                            <div class="line"></div>
                        </div>
                        <p class="text-center">Logged Out Successfully</p>
                        <div class="row mb-4 px-3"> <small class="font-weight-bold">Login Again <a class="text-danger " href="{% url 'custom_auth:login' %}">Login</a></small> </div>
                        <div class="row mb-4 px-3"> <small class="font-weight-bold">Don't have an account? <a class="text-danger " href="{% url 'custom_auth:register' %}">Register</a></small> </div>
                    </div>
                </form>
                </div>
            </div>
            <div class="bg-blue py-4">
                <div class="row px-3"> <small class="ml-4 ml-sm-5 mb-2">Copyright &copy; 2019. All rights reserved.</small>
                    <div class="social-contact ml-4 ml-sm-auto"> <span class="fa fa-facebook mr-4 text-sm"></span> <span class="fa fa-google-plus mr-4 text-sm"></span> <span class="fa fa-linkedin mr-4 text-sm"></span> <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span> </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/register.html
{% load static %}
{% load widget_tweaks %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/auth.css' %}">
    <link rel="stylesheet" href="{% static 'js/parsley.js' %}">
    <title>Login Form </title>
    <script type = "text/javascript">
   
           // Form validation code will come here.
           function validate() {
            if( document.loginform.name.value == "" ) {
                 alert( "Please provide your Name!" );
                 document.loginform.email.focus() ;
                 return false;
              }
           
              if( document.loginform.email.value == "" ) {
                 alert( "Please provide your Email!" );
                 document.loginform.email.focus() ;
                 return false;
              }
            
              if( document.loginform.password.value == "-1" ) {
                 alert( "Please provide your Password!" );
                 return false;
              }
              return( true );
           }
  
     </script>
  </head>
  <body>
    <div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
      
        <div class="card card0 border-0">
            <div class="row d-flex">
                <div class="col-lg-6">
                    <div class="card1 pb-5">
                        <div class="row"> <img src="https://i.imgur.com/CXQmsmF.png" class="logo"> </div>
                        <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <img src="https://i.imgur.com/uNGdWHi.png" class="image"> </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <form name="loginform" action="{% url 'custom_auth:register' %}" method="post"   onsubmit = "return(validate());" data-parsley-validate>
                        {% csrf_token %}
                    <div class="card2 card border-0 px-4 py-5">

                        <div class="row px-3 mb-4">
                            <div class="line"></div> 
                            <div class="line"></div>
                        </div>
                        <div class="form-group">
                          <label>Name</label>
                          {{form.name | attr:"class:form-control" }}
                      </div>
                      <div class="form-group">
                          <label>Email</label>
                          {{form.email | attr:"class:form-control" }}
                      
                      </div>
                      <div class="form-group">
                          <label>password</label>
                          {{form.password | attr:"class:form-control" }}
                      </div>
                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Register</button> </div>
                        <div class="row mb-4 px-3"> <small class="font-weight-bold">Already have Account? <a class="text-danger " href="{% url 'custom_auth:login' %}">Login</a></small> </div>
                    </div>
                </form>
                </div>
            </div>
            <div class="bg-blue py-4">
                <div class="row px-3"> <small class="ml-4 ml-sm-5 mb-2">Copyright &copy; 2019. All rights reserved.</small>
                    <div class="social-contact ml-4 ml-sm-auto"> <span class="fa fa-facebook mr-4 text-sm"></span> <span class="fa fa-google-plus mr-4 text-sm"></span> <span class="fa fa-linkedin mr-4 text-sm"></span> <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span> </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>